title: "Лаборатория XYZ"
description: "Официальный сайт лаборатории XYZ"
baseurl: "" # Если репозиторий не пользовательский, укажите "/имя-репозитория"
url: "https://ваше-имя-пользователя.github.io" # Замените на ваш URL
theme: minima # Или выберите другую тему
